### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by DummerJunge** [nobkd/replace-maps#9]
Hello, just exactly what I was searching, but how can I install this great piece of work? Zip-File is reported as broken from FF118.0.1.

**Comment by nobkd** [comment]
Hello, thank you for your interest in this browser extension.
I just submitted it for review on AMO (addons.mozilla.org)
When it gets accepted, I'll give you an update :)

**Comment by nobkd** [comment]
@DummerJunge the extension is now available here https://addons.mozilla.org/addon/replace-maps/ 🎉
